use std::time::Duration;

use teloxide::types::{
    InputRichBlock, InputRichBlockButtons, InputRichBlockParagraph, InputRichBlockSectionHeading,
    InputRichMessage, RichMessageButton, RichText, RichTextCustomEmoji, RichTextObject,
};

use crate::{
    ActionRegistry, ActionToken, ActorPolicy, ButtonLabel, Revision, StalePolicy, Ui, UiNode,
    ViewId,
};

/// Context required to render stateful buttons for one view revision.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RenderContext {
    /// Logical view owning the rendered actions.
    pub view_id: ViewId,
    /// Revision represented by this UI.
    pub revision: Revision,
    /// Actor restriction copied into every enabled button capability.
    pub actor: ActorPolicy,
    /// Stale policy copied into every enabled button capability.
    pub stale_policy: StalePolicy,
}

impl RenderContext {
    /// Creates a context for a view revision.
    #[must_use]
    pub const fn new(view_id: ViewId, revision: Revision) -> Self {
        Self {
            view_id,
            revision,
            actor: ActorPolicy::Any,
            stale_policy: StalePolicy::Reject,
        }
    }

    /// Restricts every enabled action to one Telegram user.
    #[must_use]
    pub const fn actor(mut self, actor: ActorPolicy) -> Self {
        self.actor = actor;
        self
    }

    /// Chooses how rendered actions behave when their revision is stale.
    #[must_use]
    pub const fn stale_policy(mut self, stale_policy: StalePolicy) -> Self {
        self.stale_policy = stale_policy;
        self
    }
}

/// Result of compiling a semantic UI tree into a Rich Message.
#[derive(Clone, Debug, PartialEq)]
pub struct RenderedRichMessage {
    /// Telegram-native representation ready for send/edit requests.
    pub rich_message: InputRichMessage,
    /// Enabled callback tokens created while compiling this representation.
    pub action_tokens: Vec<ActionToken>,
    /// View metadata represented by the message.
    pub view_id: ViewId,
    /// Revision represented by the message.
    pub revision: Revision,
}

/// Structural errors found before a Rich Message is sent.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RenderError {
    /// The UI has no renderable nodes.
    EmptyUi,
    /// A button row has no buttons.
    EmptyButtonRow,
    /// A button label is empty.
    EmptyButtonLabel,
    /// A custom-emoji label is missing its identifier or fallback text.
    InvalidCustomEmoji,
}

impl std::fmt::Display for RenderError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EmptyUi => formatter.write_str("UI contains no renderable nodes"),
            Self::EmptyButtonRow => formatter.write_str("button row contains no buttons"),
            Self::EmptyButtonLabel => formatter.write_str("button label cannot be empty"),
            Self::InvalidCustomEmoji => {
                formatter.write_str("custom emoji needs an id and alternative text")
            }
        }
    }
}

impl std::error::Error for RenderError {}

/// Rich Message compiler backed by an action registry.
#[derive(Clone, Debug)]
pub struct RichRenderer<A> {
    registry: ActionRegistry<A>,
    action_ttl: Option<Duration>,
}

impl<A> RichRenderer<A> {
    /// Creates a renderer using the provided registry and no default TTL.
    #[must_use]
    pub fn new(registry: ActionRegistry<A>) -> Self {
        Self {
            registry,
            action_ttl: None,
        }
    }

    /// Sets the TTL for action tokens generated by this renderer.
    #[must_use]
    pub const fn action_ttl(mut self, ttl: Option<Duration>) -> Self {
        self.action_ttl = ttl;
        self
    }

    /// Returns the registry used by this renderer.
    #[must_use]
    pub const fn registry(&self) -> &ActionRegistry<A> {
        &self.registry
    }

    /// Compiles a complete semantic UI representation.
    pub fn render(
        &self,
        ui: &Ui<A>,
        context: RenderContext,
    ) -> Result<RenderedRichMessage, RenderError>
    where
        A: Clone + Send + Sync + 'static,
    {
        validate_nodes(&ui.nodes)?;
        let mut blocks = Vec::new();
        let mut action_tokens = Vec::new();
        self.render_nodes(&ui.nodes, context, &mut blocks, &mut action_tokens);
        if blocks.is_empty() {
            return Err(RenderError::EmptyUi);
        }
        Ok(RenderedRichMessage {
            rich_message: InputRichMessage::blocks(blocks),
            action_tokens,
            view_id: context.view_id,
            revision: context.revision,
        })
    }

    fn render_nodes(
        &self,
        nodes: &[UiNode<A>],
        context: RenderContext,
        blocks: &mut Vec<InputRichBlock>,
        action_tokens: &mut Vec<ActionToken>,
    ) where
        A: Clone + Send + Sync + 'static,
    {
        for node in nodes {
            match node {
                UiNode::Text(text) | UiNode::Paragraph(text) => {
                    blocks.push(InputRichBlock::Paragraph(InputRichBlockParagraph {
                        text: RichText::from(text.as_str()),
                    }));
                }
                UiNode::Heading(text) => {
                    blocks.push(InputRichBlock::Heading(InputRichBlockSectionHeading {
                        text: RichText::from(text.as_str()),
                        size: 2,
                    }));
                }
                UiNode::ButtonRow(row) => {
                    let buttons = row
                        .buttons
                        .iter()
                        .map(|button| {
                            if button.disabled {
                                return RichMessageButton::disabled(render_button_label(
                                    &button.text,
                                ));
                            }
                            let token = self.registry.register_with_ttl(
                                context.view_id,
                                context.revision,
                                button.action.clone(),
                                context.actor,
                                context.stale_policy,
                                self.action_ttl,
                            );
                            action_tokens.push(token.clone());
                            let style = button.style;
                            let rendered = RichMessageButton::callback(
                                render_button_label(&button.text),
                                token.as_str(),
                            );
                            match style {
                                crate::ButtonStyle::Default => rendered,
                                style => rendered.style(style.as_str()),
                            }
                        })
                        .collect::<Vec<_>>();
                    blocks.push(InputRichBlock::Buttons(InputRichBlockButtons::new(buttons)));
                }
                UiNode::Fragment(children) => {
                    self.render_nodes(children, context, blocks, action_tokens)
                }
            }
        }
    }
}

fn validate_nodes<A>(nodes: &[UiNode<A>]) -> Result<(), RenderError> {
    if nodes.is_empty() {
        return Err(RenderError::EmptyUi);
    }
    for node in nodes {
        match node {
            UiNode::Text(text) | UiNode::Paragraph(text) | UiNode::Heading(text) => {
                if text.is_empty() {
                    return Err(RenderError::EmptyUi);
                }
            }
            UiNode::ButtonRow(row) => {
                if row.buttons.is_empty() {
                    return Err(RenderError::EmptyButtonRow);
                }
                for button in &row.buttons {
                    match &button.text {
                        ButtonLabel::Plain(text) if text.is_empty() => {
                            return Err(RenderError::EmptyButtonLabel);
                        }
                        ButtonLabel::CustomEmoji {
                            custom_emoji_id,
                            alternative_text,
                        } if custom_emoji_id.is_empty() || alternative_text.is_empty() => {
                            return Err(RenderError::InvalidCustomEmoji);
                        }
                        _ => {}
                    }
                }
            }
            UiNode::Fragment(children) => validate_nodes(children)?,
        }
    }
    Ok(())
}

fn render_button_label(label: &ButtonLabel) -> RichText {
    match label {
        ButtonLabel::Plain(text) => RichText::from(text.as_str()),
        ButtonLabel::CustomEmoji {
            custom_emoji_id,
            alternative_text,
        } => RichText::Object(RichTextObject::CustomEmoji(RichTextCustomEmoji {
            custom_emoji_id: custom_emoji_id.clone(),
            alternative_text: alternative_text.clone(),
        })),
    }
}

impl crate::ButtonStyle {
    fn as_str(self) -> &'static str {
        match self {
            Self::Default => "default",
            Self::Primary => "primary",
            Self::Success => "success",
            Self::Danger => "danger",
            Self::Link => "link",
        }
    }
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use teloxide::types::{RichText, RichTextObject};

    use super::{RenderContext, RenderError, RichRenderer};
    use crate::{
        ActionRegistry, ActorPolicy, ButtonLabel, ButtonStyle, Revision, StalePolicy, Ui, ViewId,
    };

    #[derive(Clone, Debug, PartialEq)]
    enum Action {
        Increment,
    }

    #[test]
    fn rich_renderer_registers_opaque_buttons_with_view_metadata() {
        let registry = ActionRegistry::new();
        let renderer =
            RichRenderer::new(registry.clone()).action_ttl(Some(Duration::from_secs(60)));
        let ui = Ui::column().push(
            Ui::button_row().push(Ui::button("+", Action::Increment).style(ButtonStyle::Success)),
        );
        let rendered = renderer
            .render(
                &ui,
                RenderContext::new(ViewId::new(4), Revision::new(9))
                    .actor(ActorPolicy::Any)
                    .stale_policy(StalePolicy::Reject),
            )
            .unwrap();
        assert_eq!(rendered.action_tokens.len(), 1);
        assert_eq!(registry.len(), 1);
        let blocks = rendered.rich_message.blocks_ref().unwrap();
        assert_eq!(blocks.len(), 1);
        assert!(matches!(
            blocks[0],
            teloxide::types::InputRichBlock::Buttons(_)
        ));
    }

    #[test]
    fn renderer_rejects_empty_button_rows_before_network() {
        let renderer = RichRenderer::new(ActionRegistry::<Action>::new());
        let ui = Ui::<Action>::column().push(Ui::button_row());
        assert_eq!(
            renderer.render(&ui, RenderContext::new(ViewId::new(1), Revision::INITIAL)),
            Err(RenderError::EmptyButtonRow)
        );
    }

    #[test]
    fn renderer_preserves_custom_emoji_button_labels() {
        let renderer = RichRenderer::new(ActionRegistry::<Action>::new());
        let ui = Ui::column().push(Ui::button_row().push(Ui::button(
            ButtonLabel::custom_emoji("emoji-id", "♔"),
            Action::Increment,
        )));
        let rendered = renderer
            .render(&ui, RenderContext::new(ViewId::new(1), Revision::INITIAL))
            .unwrap();
        let blocks = rendered.rich_message.blocks_ref().unwrap();
        let teloxide::types::InputRichBlock::Buttons(buttons) = &blocks[0] else {
            panic!("expected button block");
        };
        let RichText::Object(RichTextObject::CustomEmoji(emoji)) = &buttons.buttons[0].text else {
            panic!("expected custom emoji label");
        };
        assert_eq!(emoji.custom_emoji_id, "emoji-id");
        assert_eq!(emoji.alternative_text, "♔");
    }
}
